const bodyParser = require("body-parser")
const express = require("express")
const { router } = require("./router/router")
const app = express()
const cors = require("cors")
app.use(cors())

app.use(express.json())
app.use(express.static("public"))
app.use(router)
app.listen(9000)
